### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by dmzx** [rmcgirr83/prunepms#2]
https://github.com/rmcgirr83/prunepms/blob/f8d603e73113f6aa3f24a7bf36aecddd0a2bcef5/adm/style/acp_prunepms.html#L31

https://github.com/rmcgirr83/prunepms/blob/f8d603e73113f6aa3f24a7bf36aecddd0a2bcef5/adm/style/acp_prunepms.html#L36

Criteria and before are not declared in language file. Is this done with a purpose?

**Comment by rmcgirr83** [comment]
They are already set in the ACP lang files.

**Comment by dmzx** [comment]
Yes in $user->add_lang('acp/prune'); & $user->add_lang('memberlist'); i see, but you not call them. 
Tested on 3.3.0

**Comment by rmcgirr83** [comment]
Thanks again, fixed.  New version coming soonish.
